name: ESLint

on:
  pull_request:
    branches:
      - main  # Change this to your main branch name if it's different

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Change working directory
        run: cd UniSign

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint .
